"""Commands package."""

from .system import (
    ping_handler,
    info_handler,
    help_handler,
    restart_handler,
    update_handler,
    stop_handler,
    VERSION,
    command_prefix,
    power_save_mode,
    start_time,
)
from .modules import (
    im_handler,
    dlm_handler,
    dlml_handler,
    lm_handler,
    um_handler,
    unlm_handler,
)
from .settings import (
    prefix_handler,
    alias_handler,
    lang_handler,
    theme_handler,
    logs_handler,
    rollback_handler,
    powersave_handler,
    menu_handler,
    confirm_handler,
    handler_2fa,
    aliases,
    power_save_mode as ps_power_save_mode,
)
from .utility import t_handler, ibot_handler

__all__ = [
    "ping_handler",
    "info_handler",
    "help_handler",
    "restart_handler",
    "update_handler",
    "stop_handler",
    "im_handler",
    "dlm_handler",
    "dlml_handler",
    "lm_handler",
    "um_handler",
    "unlm_handler",
    "prefix_handler",
    "alias_handler",
    "lang_handler",
    "theme_handler",
    "logs_handler",
    "rollback_handler",
    "powersave_handler",
    "menu_handler",
    "confirm_handler",
    "handler_2fa",
    "t_handler",
    "ibot_handler",
    "VERSION",
    "command_prefix",
    "aliases",
    "power_save_mode",
    "start_time",
]